name: Lighthouse Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to test'
        required: false
        default: 'https://bd-theme-nu.vercel.app'
      device:
        description: 'Device type'
        required: false
        default: 'desktop'
        type: choice
        options:
          - desktop
          - mobile

jobs:
  lighthouse:
    name: Lighthouse Performance Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for deployment (if needed)
        if: github.event_name == 'push'
        run: |
          echo "Waiting 60 seconds for deployment to be ready..."
          sleep 60

      - name: Run Lighthouse Tests (Desktop)
        run: |
          npm run test:lighthouse:quick
        env:
          SITE_URL: ${{ github.event.inputs.url || 'https://bd-theme-nu.vercel.app' }}

      - name: Run Lighthouse Tests (Mobile)
        run: |
          npx unlighthouse --site ${{ github.event.inputs.url || 'https://bd-theme-nu.vercel.app' }} --samples 3 --device mobile --output-path ./lighthouse-reports-mobile

      - name: Upload Lighthouse Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-reports-${{ github.run_id }}
          path: |
            lighthouse-reports/
            lighthouse-reports-mobile/
          retention-days: 30

      - name: Comment PR with Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Try to read summary results
            let summaryMessage = '🚀 **Lighthouse Performance Results**\n\n';
            summaryMessage += `📊 Tested URL: ${{ github.event.inputs.url || 'https://bd-theme-nu.vercel.app' }}\n`;
            summaryMessage += `🔗 Full reports will be available in the GitHub Actions artifacts.\n\n`;
            summaryMessage += '> Performance tests completed. Check the Actions tab for detailed reports.';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summaryMessage
            });

  performance-budget:
    name: Performance Budget Check
    runs-on: ubuntu-latest
    needs: lighthouse
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Performance Budget Check
        run: |
          npm run test:lighthouse:ci
        continue-on-error: true

      - name: Performance Budget Results
        if: always()
        run: |
          echo "Performance budget check completed"
          echo "Check the artifacts for detailed results"